### ISSUE TITLE
Serve page through https

### ISSUE THREAD

**Issue by blueyed** [Nagasaki45/krihelinator#58]
To allow inclusion of the badge in project's READMEs (https://github.com/Nagasaki45/krihelinator/issues/57) it is necessary for them to be hosted on https, since e.g. GitHub is using it, and then http resources won't be included.

I recommend to use https://letsencrypt.org/ for this.

**Comment by Nagasaki45** [comment]
Moving everything to https will be great, but I don't see any problem to present the bandge on project's READMEs on GitHub. See examples [here](https://github.com/nagasaki45/krihelinator) and [here](https://github.com/shirax/vmap).

Am I missing something?

**Comment by blueyed** [comment]
Oh, GitHub appears to wrap/cache it.
Now included in https://github.com/neomake/neomake/blob/master/README.md, too.
Thanks.

Keeping this issue open for the https support though.

**Comment by Nagasaki45** [comment]
With the current docker based deployment, that complicates the task significantly, there is very small value to effort ratio in implementation this. I will keep the ticket open but won't work on it soon.

**Comment by Nagasaki45** [comment]
Got an email from google (search console) saying that any page with a form that is not served through https will soon (October) raise a "Not secure" warning on chrome. So, this issue became kind of urgent.
