### ISSUE TITLE
Change the badge design

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/krihelinator#71]
The only user of the badge removed it as it displayed as red :-(

https://github.com/neomake/neomake/commit/f9ee9616f8846e2c9b5cf2cd9d2597a6c8a41582

@blueyed, if you have specific suggestions I would like to hear them.

**Comment by blueyed** [comment]
Thanks! :)

I wasn't aware to be the only user.. ;)

Regarding improved usefulness I think https://github.com/Nagasaki45/krihelinator/issues/57 would need to be addressed also.

**Comment by Nagasaki45** [comment]
Yes, I agree, implementing #57 is more important than the cosmetic changes I just made.

However, I don't think that it is feasible to add any kind of dropdown functionality in github's markdown files. Let's say that the CSS layout part is less problematic, as I can take a snapshot of the information and give a link to it. But still, there's no way to show it upon clicking the badge.
